# Generated by Django 2.2.12 on 2022-04-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.BooleanField()),
                ('pref', models.CharField(max_length=200)),
                ('jyob', models.CharField(max_length=200)),
                ('pojishon', models.CharField(max_length=200)),
            ],
        ),
    ]
